name: Generate formulae.brew.sh data.

on: push

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          brew update-reset "$(brew --repository)"
          brew tap "$GITHUB_REPOSITORY"
          brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"

          git clone --depth=1 https://github.com/Homebrew/formulae.brew.sh
          cd formulae.brew.sh

          /usr/bin/bundle install --jobs 4 --retry 3
          /usr/bin/bundle exec rake

          # commit and push generated files
          git add _data/formula api/formula formula

          git diff --exit-code HEAD -- _data/analytics _data/formula api/formula formula cask
